{
 "title": "tbw_node_monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hardware Stats", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Delegate stats", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 13, "y": 0 } },
  {
   "title": "Reboot Needed?",
   "type": "stat",
   "description": "This will turn red when your system needs to be rebooted because of security updates.\n\nSetting this up is Operating System specific, so it doesn't come ready out of the box; see the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_reboot_required{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "description": "Tracks any updates that are available for your OS or for Rocket Pool but haven't been applied yet. When one of these numbers is higher than 0, it means you should update your system or Rocket Pool accordingly.\n\nSetting this up is Operating System specific, so it doesn't come ready out of the box; see the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(os_upgrades_pending{job=\"node\"})",
     "legendFormat": "OS"
    },
    {
     "expr": "max(rocketpool_version_update{job=\"node\"})",
     "legendFormat": "Rocket Pool"
    }
   ]
  },
  {
   "title": "Delegate rank",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbw_delegate_data{delegate=\"delegate_rank\"}",
     "legendFormat": "Delegate rank"
    }
   ]
  },
  {
   "title": "Forged block",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(tbw_delegate_data{delegate=\"delegate_forged_block\"})",
     "legendFormat": "Forged block"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "description": "The total CPU usage of your machine, with respect to all cores.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "description": "The temperature of your CPU (you can set this to Tctl or Tdie, whichever you prefer to monitor).\n\nTo get the correct chip and sensor ID, you'll want to run `sensors` from the `lm-sensors` package. See the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}"
    }
   ]
  },
  {
   "title": "Swap Space Usage",
   "type": "gauge",
   "description": "How much of your total swap space you're currently using. If you have swap space enabled, you want this to be as low as possible - otherwise, your system is running out of free RAM.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"node\"} - node_memory_SwapFree_bytes{job=\"node\"}) / node_memory_SwapTotal_bytes{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "stat",
   "description": "The total amount of RAM that your system is currently using.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "The total amount of RAM that your system has installed.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Pending payout",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_payout_data{payout=\"pending_voters_payout\"}) / sum(tbw_config_data{param=\"atomic\"})",
     "legendFormat": "voters"
    },
    {
     "expr": "sum(tbw_payout_data{payout=\"pending_delegate_payout\"}) / sum(tbw_config_data{param=\"atomic\"})",
     "legendFormat": "delegate"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Tracks the amount of CPU consumption for the eth2 client and the total system. 100% means all of your CPU core are being used at their full capacity. The yellow line indicates how much CPU a single core can provide in your system.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "Single Core Cap"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Tracks the total amount of RAM usage by the eth2 client and the entire system, versus how much is available.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"eth2\"}) + sum(process_resident_memory_bytes{job=\"validator\"})",
     "legendFormat": "Lighthouse"
    }
   ]
  },
  {
   "title": "Block before payout",
   "type": "stat",
   "description": "block number until your next payout.\n\n**NOTE: Lighthouse does not currently expose this metric, so this is a placeholder until its developers add it.**",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbw_payout_data{payout=\"block_before_payout\"}"
    }
   ]
  },
  {
   "title": "Time of last forged block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - tbw_delegate_data{delegate=\"delegate_last_t_forged\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "description": "How many peers Lighthouse is currently connected to for Beacon Chain traffic.",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbw_network_data{network=\"peers_number\"}"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "timeseries",
   "description": "This tracks how long it takes between one of your processes trying to read from / write to your SSD, and when that operation is actually performed. Think of this like \"how long SSD reads and writes have to wait in a queue before completing\". The longer this time, the longer it takes for your node to perform its Beacon Chain duties.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "OS Disk Space Used",
   "type": "gauge",
   "description": "The disk space used by your primary (Operating System) hard drive. Change the `device` option in this query to be your machine's hard drive.\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Disk 2 Space Used",
   "type": "gauge",
   "description": "An optional space monitor for a second disk or partition on your system. If you store your chain data on a separate drive or partition from your OS (such as with a Raspberry Pi), you can configure this to track that disk. Just modify the `device` setting in the query with your storage partition's path.\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\"} - node_filesystem_avail_bytes{job=\"node\"}) / node_filesystem_size_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Total distributed rewards",
   "type": "stat",
   "description": "block number until your next payout.\n\n**NOTE: Lighthouse does not currently expose this metric, so this is a placeholder until its developers add it.**",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_payout_data{payout=\"total_delegate_rewards\"}) / sum(tbw_config_data{param=\"atomic\"})",
     "legendFormat": "Delegate"
    },
    {
     "expr": "sum(tbw_payout_data{payout=\"total_voters_rewards\"}) / sum(tbw_config_data{param=\"atomic\"})",
     "legendFormat": "Voters"
    }
   ]
  },
  {
   "title": "SSD Latency",
   "type": "timeseries",
   "description": "The average read/write latency of your SSD. The lower it is, the faster your machine can process and respond to Beacon Chain activities like attesting. Change the `device` setting in the queries to be the SSD you want to track (typically the one with your chain data on it).\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"node\"}[$__rate_interval])",
     "legendFormat": "Write"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"node\"}[$__rate_interval])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "A chart showing the network I/O used by your main network adapter over time. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\"}[$__rate_interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 9, "x": 13, "y": 20 }, "options": { "content": "<br/>s" } },
  {
   "title": "Total Net I/O",
   "type": "stat",
   "description": "The total network I/O that has gone through your main network adapter. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"node\"}",
     "legendFormat": "Tx"
    },
    {
     "expr": "node_network_receive_bytes_total{job=\"node\"}",
     "legendFormat": "Rx"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 28 } }
 ]
}