version: "3.4"
services:
  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: ${COMPOSE_PROJECT_NAME}_alertmanager
    restart: unless-stopped
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "${ALERTMANAGER_PORT:-9093}:${ALERTMANAGER_PORT:-9093}/tcp"
    volumes:
      - "../alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - "../alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl"
    networks:
      - net
networks:
  net:
volumes:
  alertmanager-data:
