version: "3.4"
services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: ${COMPOSE_PROJECT_NAME}_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - net
# Uncomment the lines below if you want to expose Prometheus to your local network, so other machines can access it
#    ports:
#      - target: 8080
#        published: 9338
#        protocol: tcp
    labels:
      org.label-schema.group: "monitoring"
networks:
  net:
