global:
  scrape_interval:     45s
  evaluation_interval: 2m

rule_files:
  - "/etc/prometheus/alert_rules/alert_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'
    scheme: http
    timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9103', 'host.docker.internal:9104', 'host.docker.internal:9338']
