global:
  resolve_timeout: 5m

route:
 group_by: ['...']
 receiver: telegram

receivers:
- name: telegram
  telegram_configs:
  - bot_token: 'XXXXX'
    api_url: 'https://api.telegram.org'
    message: '{{ template "custom_telegram" . }}'
    chat_id: 1234
    send_resolved: true

templates:
  - '/etc/alertmanager/templates/default.tmpl'
